# Configuration settings that affect the entire site. These values are generally
# expected to be set up once, and rarely changed after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when using
# `jekyll serve`. If you make changes to this file, you will need to restart the
# local server.

# Project settings
theme: jekyll-theme-primer
title: &title PokeTwo
description: The Unofficial FAQ for the PokéOne Game

# Compatibility named variables
# These exist to provide consistency with expectations from plugins.
name: *title

# Project rendering settings
title_separator: "-"

# Date settings
date_format: "%b %-d, %Y"

# url settings
# baseurl: ""                # the subpath of your site, e.g. /blog
# url: "https://pokeone.com" # baseline & protocol of the site, without trailing slash

# Analytics
google_analytics: UA-48212212-8

# Handling Reading
include: ["_pages"]

# Collections
collections:

# Plugins (previously gems)
plugins:
  # default plugins
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

  # custom plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
