theme: jekyll-theme-primer
title: PokeTwo
description: The Unofficial FAQ for the PokéOne Game

# HTTPS Urls
# url settings
baseurl: ""                # the subpath of your site, e.g. /blog
url: "https://pokeone.com" # baseline & protocol of the site, without trailing slash

google_analytics: UA-48212212-8

plugins:
  # default plugins
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

  # custom plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Ensure pokemon get indexed
include: ["pokemon"]
